const SECRET = JSON.parse(process.env.SECRET as string)

export const BOT_WATCHER_ROLE = '<@&987030632704118835>'
export const RUNS_TO_LOG_AFTER = 30

export const CRON_REBALANCE = '0 0 * * *'
export const CRON_CLOSE_TOKEN_POSITION = '*/30 * * * *'

export const ARB_GAS_UPPER_BOUND = 1_500_000

export const PRE_FLIGHT_CHECK = {
  FTX_BALANCE_THRESHOLD: 100,
  ARB_ETH_BAL_THRESHOLD: 0.1,
  RAGETRADE_BAL_THRESHOLD: 100 * 10 ** 6,
  BLOCK_TIMESTAMP_FRESHNESS_THRESHOLD: 4 * 60,
}

export const NETWORK_INF0 = {
  // chains
  CHAIN_ID: 42161,
  // block explorer
  BLOCK_EXPLORER_URL: 'https://arbiscan.io/',
  BLOCK_EXPLORER_API: SECRET.BLOCK_EXPLORER_API as string,
  PK_VAULT_REBALANCE: SECRET.PK_VAULT_REBALANCE as string,
  // private keys
  PK_LIQUIDATION: SECRET.PK_LIQUIDATION as string,
  PK_PRICE_ARB_BOT: SECRET.PK_PRICE_ARB_BOT as string,
  PK_HEDGE_STRATEGY: SECRET.PK_HEDGE_STRATEGY as string,
  PK_FUNDING_ARB_BOT: SECRET.PK_FUNDING_ARB_BOT as string,
  PK_DN_VAULT_REBALANCE: SECRET.PK_DN_VAULT_REBALANCE as string,
  PK_GLP_BATCHING_MANAGER: SECRET.PK_GLP_BATCHING_MANAGER as string,
  PK_USDC_BATCHING_MANAGER: SECRET.PK_USDC_BATCHING_MANAGER as string,
  // rpcs
  WSS_RPC_URL: SECRET.WSS_RPC_URL as string,
  HTTP_RPC_URL: SECRET.HTTP_RPC_URL as string,
  // logging
  ARB_BOT_WEBHOOK_URL: SECRET.ARB_BOT_WEBHOOK_URL as string,
  REBALANCE_DN_WEBHOOK_URL: SECRET.REBALANCE_WEBHOOK_URL as string,
  REBALANCE_80_20_WEBHOOK_URL: SECRET.REBALANCE_WEBHOOK_URL as string,
  LIQUIDATION_WEBHOOK_URL: SECRET.LIQUIDATION_WEBHOOK_URL as string,
  HEDGE_STRATEGY_WEBHOOK_URL: SECRET.HEDGE_STRATEGY_WEBHOOK_URL as string,
  GLP_BATCHING_MANAGER_WEBHOOK_URL: SECRET.GLP_BATCHING_MANAGER_WEBHOOK_URL as string,
  USDC_BATCHING_MANAGER_WEBHOOK_URL: SECRET.USDC_BATCHING_MANAGER_WEBHOOK_URL as string,
}

export const AMM_CONFIG = {
  FEE: 0.0015,
  POOL_ID: 2721558366,
  PRICE_ARB_ACCOUNT_ID: Number(SECRET.PRICE_ARB_ACCOUNT_ID as string),
  FUNDING_ARB_ACCOUNT_ID: Number(SECRET.FUNDING_ARB_ACCOUNT_ID as string) || 0,
}

export const FTX_CONFIG = {
  FEE: 0.000665,
  SCALING_FACTOR: 1,
  MARKET_ID: 'ETH-PERP',
  PRICE_ARB_ACCOUNT: {
    SUB_ACCOUNT_ID: SECRET.SUB_ACCOUNT_ID as string,
    ACCESS_KEY: SECRET.ACCESS_KEY as string,
    ACCESS_SECRET: SECRET.ACCESS_SECRET as string,
  },
  FUNDING_ARB_ACCOUNT: {
    SUB_ACCOUNT_ID: '',
    ACCESS_KEY: '',
    ACCESS_SECRET: '',
  },
}

export const STRATERGY_CONFIG = {
  FREQUENCY: 30,
  MIN_NOTIONAL_PROFIT: 1,
  SOFT_MARGIN_RATIO_THRESHOLD: 0.5,
  HARD_MARGIN_RATIO_THRESHOLD: 0.25,
}
