export const PRE_FLIGHT_CHECK = {
  FTX_BALANCE_THRESHOLD: 95,
  ARB_ETH_BAL_THRESHOLD: 0.1,
  RAGETRADE_BAL_THRESHOLD: 100 * 10 ** 6,
  BLOCK_TIMESTAMP_FRESHNESS_THRESHOLD: 10 * 60,
}

export const NETWORK_INF0 = {
  CHAIN_ID: 421611,
  BLOCK_EXPLORER_URL: 'https://testnet.arbiscan.io/',
  ALCHEMY_API_KEY: '',
  BLOCK_EXPLORER_API: '',
  PK_VAULT_REBALANCE: '',
  PK_LIQUIDATTION: '',
  PK_PRICE_ARB_BOT: '',
  PK_FUNDING_ARB_BOT: '',
  WSS_RPC_URL: '',
  HTTP_RPC_URL: '',
  ARB_BOT_WEBHOOK_URL: '',
  REBALANCE_WEBHOOK_URL: '',
  LIQUIDATION_WEBHOOK_URL: '',
}

export const AMM_CONFIG = {
  FEE: 0.0015,
  ACCOUNT_ID: 0,
  POOL_ID: 0,
}

export const FTX_CONFIG = {
  FEE: 0.000665,
  SCALING_FACTOR: 1000,
  MARKET_ID: 'ETH-PERP',
  SUB_ACCOUNT_ID: '',
  ACCESS_KEY: '',
  ACCESS_SECRET: '',
}

export const STRATERGY_CONFIG = {
  FREQUENCY: 30,
  MIN_NOTIONAL_PROFIT: 3,
  SOFT_MARGIN_RATIO_THRESHOLD: 0.5,
  HARD_MARGIN_RATIO_THRESHOLD: 0.25,
}
