export const PRE_FLIGHT_CHECK = {
  FTX_BALANCE_THRESHOLD: 95,
  ARB_ETH_BAL_THRESHOLD: 0.1,
  RAGETRADE_BAL_THRESHOLD: 100 * 10 ** 6,
  BLOCK_TIMESTAMP_FRESHNESS_THRESHOLD: 10 * 60,
}

export const NETWORK_INF0 = {
  CHAIN_ID: 421611,
  BLOCK_EXPLORER_URL: 'https://testnet.arbiscan.io/',
  BLOCK_EXPLORER_API: process.env.BLOCK_EXPLORER_API as string,
  PK_VAULT_REBALANCE: process.env.PK_VAULT_REBALANCE as string,
  PK_LIQUIDATION: process.env.PK_LIQUIDATION as string,
  PK_PRICE_ARB_BOT: process.env.PK_PRICE_ARB_BOT as string,
  PK_FUNDING_ARB_BOT: process.env.PK_FUNDING_ARB_BOT as string,
  WSS_RPC_URL: process.env.WSS_RPC_URL as string,
  HTTP_RPC_URL: process.env.HTTP_RPC_URL as string,
  ARB_BOT_WEBHOOK_URL: process.env.ARB_BOT_WEBHOOK_URL as string,
  REBALANCE_WEBHOOK_URL: process.env.REBALANCE_WEBHOOK_URL as string,
  LIQUIDATION_WEBHOOK_URL: process.env.LIQUIDATION_WEBHOOK_URL as string,
}

export const AMM_CONFIG = {
  FEE: 0.0015,
  POOL_ID: 2277115137,
  PRICE_ARB_ACCOUNT_ID: Number(process.env.PRICE_ARB_ACCOUNT_ID as string),
  FUNDING_ARB_ACCOUNT_ID: Number(process.env.FUNDING_ARB_ACCOUNT_ID as string) || 0
}

export const FTX_CONFIG = {
  FEE: 0.000665,
  SCALING_FACTOR: 1000,
  MARKET_ID: 'ETH-PERP',
  PRICE_ARB_ACCOUNT: {
    SUB_ACCOUNT_ID: process.env.SUB_ACCOUNT_ID as string,
    ACCESS_KEY: process.env.ACCESS_KEY as string,
    ACCESS_SECRET: process.env.ACCESS_SECRET as string,
  },
  FUNDING_ARB_ACCOUNT: {
    SUB_ACCOUNT_ID: '',
    ACCESS_KEY: '',
    ACCESS_SECRET: '',
  }
}

export const STRATERGY_CONFIG = {
  FREQUENCY: 30,
  MIN_NOTIONAL_PROFIT: 5,
  SOFT_MARGIN_RATIO_THRESHOLD: 0.5,
  HARD_MARGIN_RATIO_THRESHOLD: 0.25,
}
