version: '3.4'
services:
  arb-bot:
    build:
      context: .
      target: arb-bot
  vault-rebalance:
    build:
      context: .
      target: vault-rebalance
  keeper-liquidation:
    build:
      context: .
      target: keeper-liquidation
