version: '3.4'
services:
  vault-rebalance:
    build:
      context: .
      target: vault-rebalance
  vault-rebalance-gmx:
    build:
      context: .
      target: vault-rebalance-gmx
  batching-manager:
    build:
      context: .
      target: batching-manager
  keeper-liquidation:
    build:
      context: .
      target: keeper-liquidation
  usdc-batching-manager:
    build:
      context: .
      target: usdc-batching-manager
  glp-batching-manager:
    build:
      context: .
      target: glp-batching-manager
  dn-rebalance:
    build:
      context: .
      target: dn-rebalance
  hedge-strategy:
    build:
      context: .
      target: hedge-strategy
  jit-keeper:
    build:
      context: .
      target: jit-keeper
