version: '3.4'
services:
  arb-bot:
    build:
      context: .
      target: arb-bot
  vault-rebalance:
    build:
      context: .
      target: vault-rebalance
  vault-rebalance-gmx:
    build:
      context: .
      target: vault-rebalance-gmx
  batching-manager:
    build:
      context: .
      target: batching-manager
  keeper-liquidation:
    build:
      context: .
      target: keeper-liquidation
  oracles:
    build:
      context: .
      target: oracles
