module.exports = [
  {
    script: 'dist/arbitrage-bot/execute.js',
    name: 'arb-bot',
    out_file: '.pm2/logs/output.log',
    error_file: '.pm2/logs/error.log',
    combine_logs: true,
    merge_logs: true,
  },
  {
    script: 'dist/keeper-liquidation/index.js',
    name: 'keeper-liquidation',
    out_file: '.pm2/logs/output.log',
    error_file: '.pm2/logs/error.log',
    combine_logs: true,
    merge_logs: true,
  },
  {
    script: 'dist/vault-rebalance/index.js',
    name: 'vault-rebalance',
    out_file: '.pm2/logs/output.log',
    error_file: '.pm2/logs/error.log',
    combine_logs: true,
    merge_logs: true,
  },
  {
    script: 'dist/batching-manager/usdc-batching-manager.js',
    name: 'usdc-batching-manager',
    out_file: '.pm2/logs/output.log',
    error_file: '.pm2/logs/error.log',
    combine_logs: true,
    merge_logs: true,
  },
  {
    script: 'dist/batching-manager/glp-batching-manager.js',
    name: 'glp-batching-manager',
    out_file: '.pm2/logs/output.log',
    error_file: '.pm2/logs/error.log',
    combine_logs: true,
    merge_logs: true,
  },
  {
    script: 'dist/vault-rebalance/dn.js',
    name: 'dn-rebalance',
    out_file: '.pm2/logs/output.log',
    error_file: '.pm2/logs/error.log',
    combine_logs: true,
    merge_logs: true,
  },
  {
    script: 'dist/hedge-strategy/index.js',
    name: 'hedge-strategy',
    out_file: '.pm2/logs/output.log',
    error_file: '.pm2/logs/error.log',
    combine_logs: true,
    merge_logs: true,
  }
]
